// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getChatHistory = `-- name: GetChatHistory :many
SELECT prompt, response FROM chat
WHERE session_id = $1
ORDER BY created_at ASC
`

type GetChatHistoryRow struct {
	Prompt   sql.NullString
	Response sql.NullString
}

func (q *Queries) GetChatHistory(ctx context.Context, sessionID uuid.NullUUID) ([]GetChatHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getChatHistory, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatHistoryRow
	for rows.Next() {
		var i GetChatHistoryRow
		if err := rows.Scan(&i.Prompt, &i.Response); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNewChat = `-- name: SaveNewChat :one
INSERT INTO chat(id, session_id, prompt, response, created_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW()
)
RETURNING id, session_id, prompt, response, created_at
`

type SaveNewChatParams struct {
	SessionID uuid.NullUUID
	Prompt    sql.NullString
	Response  sql.NullString
}

func (q *Queries) SaveNewChat(ctx context.Context, arg SaveNewChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, saveNewChat, arg.SessionID, arg.Prompt, arg.Response)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Prompt,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}
