// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getChatHistory = `-- name: GetChatHistory :one
SELECT id, session_id, prompt, response, created_at FROM chat
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetChatHistory(ctx context.Context, sessionID uuid.NullUUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatHistory, sessionID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Prompt,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const saveNewChat = `-- name: SaveNewChat :one
INSERT INTO chat(id, session_id, prompt, response, created_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW()
)
RETURNING id, session_id, prompt, response, created_at
`

type SaveNewChatParams struct {
	SessionID uuid.NullUUID
	Prompt    sql.NullString
	Response  sql.NullString
}

func (q *Queries) SaveNewChat(ctx context.Context, arg SaveNewChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, saveNewChat, arg.SessionID, arg.Prompt, arg.Response)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Prompt,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const updateTable = `-- name: UpdateTable :one
UPDATE chat
SET response = $1
WHERE id = $2
RETURNING id, session_id, prompt, response, created_at
`

type UpdateTableParams struct {
	Response sql.NullString
	ID       uuid.UUID
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, updateTable, arg.Response, arg.ID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Prompt,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}
