// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversation_messages
WHERE session_id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, sessionID)
	return err
}

const getConversationHistory = `-- name: GetConversationHistory :many
SELECT id, session_id, role, content, message_order, created_at FROM conversation_messages
WHERE session_id = $1
ORDER BY message_order ASC
`

func (q *Queries) GetConversationHistory(ctx context.Context, sessionID uuid.UUID) ([]ConversationMessage, error) {
	rows, err := q.db.QueryContext(ctx, getConversationHistory, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationMessage
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.MessageOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationMessageCount = `-- name: GetConversationMessageCount :one
SELECT COUNT(*) FROM conversation_messages
WHERE session_id = $1
`

func (q *Queries) GetConversationMessageCount(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getConversationMessageCount, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const saveConversationMessage = `-- name: SaveConversationMessage :one
INSERT INTO conversation_messages(id, session_id, role, content, message_order, created_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    COALESCE((SELECT MAX(message_order) FROM conversation_messages WHERE session_id = $1), 0) + 1,
    NOW()
)
RETURNING id, session_id, role, content, message_order, created_at
`

type SaveConversationMessageParams struct {
	SessionID uuid.UUID
	Role      string
	Content   string
}

func (q *Queries) SaveConversationMessage(ctx context.Context, arg SaveConversationMessageParams) (ConversationMessage, error) {
	row := q.db.QueryRowContext(ctx, saveConversationMessage, arg.SessionID, arg.Role, arg.Content)
	var i ConversationMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.MessageOrder,
		&i.CreatedAt,
	)
	return i, err
}
