// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emails.sql

package database

import (
	"context"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails(id, created_at, email_text)
VALUES(
    gen_random_uuid(),
    NOW(),
    $1
)
RETURNING id, created_at, email_text
`

func (q *Queries) CreateEmail(ctx context.Context, emailText string) (Email, error) {
	row := q.db.QueryRowContext(ctx, createEmail, emailText)
	var i Email
	err := row.Scan(&i.ID, &i.CreatedAt, &i.EmailText)
	return i, err
}
