// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emails.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails(id, created_at, email_text)
VALUES(
    gen_random_uuid(),
    NOW(),
    $1
)
RETURNING id, created_at, email_text
`

func (q *Queries) CreateEmail(ctx context.Context, emailText string) (Email, error) {
	row := q.db.QueryRowContext(ctx, createEmail, emailText)
	var i Email
	err := row.Scan(&i.ID, &i.CreatedAt, &i.EmailText)
	return i, err
}

const getEmailById = `-- name: GetEmailById :one
SELECT email_text FROM emails
WHERE id = $1
`

func (q *Queries) GetEmailById(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getEmailById, id)
	var email_text string
	err := row.Scan(&email_text)
	return email_text, err
}
