// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: model_response.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addResponse = `-- name: AddResponse :one
INSERT INTO model_response(id, model, created_at, response, email_id)
VALUES(
    gen_random_uuid(),
    $1,
    NOW(),
    $2,
    $3
)
RETURNING id, model, created_at, response, email_id
`

type AddResponseParams struct {
	Model    sql.NullString
	Response string
	EmailID  uuid.UUID
}

func (q *Queries) AddResponse(ctx context.Context, arg AddResponseParams) (ModelResponse, error) {
	row := q.db.QueryRowContext(ctx, addResponse, arg.Model, arg.Response, arg.EmailID)
	var i ModelResponse
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.CreatedAt,
		&i.Response,
		&i.EmailID,
	)
	return i, err
}
