// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Email struct {
	ID        uuid.UUID
	CreatedAt time.Time
	EmailText string
}

type Session struct {
	ID        uuid.UUID
	EmailID   uuid.UUID
	CreatedAt time.Time
}

type TableVersion struct {
	ID            uuid.UUID
	SessionID     uuid.NullUUID
	CreatedAt     time.Time
	ResponseJson  json.RawMessage
	VersionNumber int32
	IsActive      sql.NullBool
}
