// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Email struct {
	ID        uuid.UUID
	CreatedAt time.Time
	EmailText string
}

type ModelResponse struct {
	ID        uuid.UUID
	Model     sql.NullString
	CreatedAt time.Time
	Response  string
	EmailID   uuid.UUID
}
