// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createNewSession = `-- name: CreateNewSession :one
INSERT INTO session(id, email_id, created_at)
VALUES(
    gen_random_uuid(),
    $1,
    NOW()
)
RETURNING id, email_id, created_at
`

func (q *Queries) CreateNewSession(ctx context.Context, emailID uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, createNewSession, emailID)
	var i Session
	err := row.Scan(&i.ID, &i.EmailID, &i.CreatedAt)
	return i, err
}

const getAllSessions = `-- name: GetAllSessions :many
SELECT id, email_id, created_at FROM session
ORDER BY created_at ASC
`

func (q *Queries) GetAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(&i.ID, &i.EmailID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, email_id, created_at FROM session
WHERE id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(&i.ID, &i.EmailID, &i.CreatedAt)
	return i, err
}
