// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: table_version.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createTableVersion = `-- name: CreateTableVersion :one
INSERT INTO table_version(id, session_id, created_at, response_json, version_number, is_active)
VALUES(
    gen_random_uuid(),
    $1,
    NOW(),
    $2,
    1,
    TRUE
)
RETURNING id, session_id, created_at, response_json, version_number, is_active
`

type CreateTableVersionParams struct {
	SessionID    uuid.NullUUID
	ResponseJson json.RawMessage
}

func (q *Queries) CreateTableVersion(ctx context.Context, arg CreateTableVersionParams) (TableVersion, error) {
	row := q.db.QueryRowContext(ctx, createTableVersion, arg.SessionID, arg.ResponseJson)
	var i TableVersion
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CreatedAt,
		&i.ResponseJson,
		&i.VersionNumber,
		&i.IsActive,
	)
	return i, err
}

const getTableBasedOnSession = `-- name: GetTableBasedOnSession :one
SELECT id, session_id, created_at, response_json, version_number, is_active FROM table_version
WHERE session_id = $1 AND is_active = TRUE
`

func (q *Queries) GetTableBasedOnSession(ctx context.Context, sessionID uuid.NullUUID) (TableVersion, error) {
	row := q.db.QueryRowContext(ctx, getTableBasedOnSession, sessionID)
	var i TableVersion
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CreatedAt,
		&i.ResponseJson,
		&i.VersionNumber,
		&i.IsActive,
	)
	return i, err
}
